In [1]:
import os
import sys

sys.path.append(os.path.join(os.getcwd(), ".."))

from data_loader import load_user, load_user_item, load_item

In [2]:
user_df = load_user(local_read=True)
user_df

,user_id,num_reviews,avg_rating_given,rating_std,min_rating_given,max_rating_given,first_review_date,last_review_date,total_recency_weight,total_helpful_votes_received,...,extreme_rating_ratio,positive_rating_ratio,negative_rating_ratio,avg_price_purchased,free_app_ratio,days_active,reviews_per_day,verified_purchase_ratio,user_segment,is_discriminating
0,ae223tlcv274eett6yjjoj4imcza,3,4.666667,0.577350,4,5,2012-01-09,2014-03-30,0.000208,1,...,0.666667,1.0,0.0,0.0000,1.000000,812,0.003695,1.000000,occasional,False
1,ae224gvo7ohtyf26u6er6beviuaq,1,5.000000,0.000000,5,5,2016-07-04,2016-07-04,0.001218,3,...,1.000000,1.0,0.0,0.0000,1.000000,1,1.000000,1.000000,one_time,False
2,ae22567o4nhejdeaxmkgeha24bwa,1,5.000000,0.000000,5,5,2016-03-11,2016-03-11,0.000889,0,...,1.000000,1.0,0.0,29.9500,0.000000,1,1.000000,1.000000,one_time,False
3,ae225j6y3ofuckvvcrdhxlzkdula,1,5.000000,0.000000,5,5,2019-10-18,2019-10-18,0.032637,1,...,1.000000,1.0,0.0,2.9900,0.000000,1,1.000000,1.000000,one_time,False
4,ae227rva23epod52v7j7ccryihbq,1,3.000000,0.000000,3,3,2012-03-19,2012-03-19,0.000017,1,...,0.000000,0.0,0.0,0.0000,1.000000,1,1.000000,1.000000,one_time,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92553,ahzzy3ar4ogdfqgsassvc2rv2s6a,5,5.000000,0.000000,5,5,2015-07-13,2021-05-23,0.285057,2,...,1.000000,1.0,0.0,8.9940,0.400000,2142,0.002334,1.000000,occasional,False
92554,ahzzy6mrmu6pa6yhuwphnrfo47qq,6,4.833333,0.408248,4,5,2012-03-20,2012-12-30,0.000160,8,...,0.833333,1.0,0.0,1.1650,0.833333,286,0.020979,0.833333,occasional,False
92555,ahzzysil4dhzzl454sqq37wok4gq,1,5.000000,0.000000,5,5,2017-11-29,2017-11-29,0.004962,1,...,1.000000,1.0,0.0,0.0000,0.000000,1,1.000000,1.000000,one_time,False
92556,ahzzzuba3pttfi67ios2mftjavea,1,5.000000,0.000000,5,5,2014-12-31,2014-12-31,0.000269,1,...,1.000000,1.0,0.0,0.0000,1.000000,1,1.000000,1.000000,one_time,False
92557,ahzzzy4dflawpbqyfqfwvacngura,4,4.500000,0.577350,4,5,2016-06-03,2016-08-19,0.004955,37,...,0.500000,1.0,0.0,0.2475,0.750000,78,0.051282,1.000000,occasional,False

In [3]:
item_df = load_item(local_read=True)
item_df

,parent_asin,item_title,main_category,categories,description,features,details,item_images,item_videos,item_rating,...,total_helpful_votes,avg_helpful_votes,num_verified_reviews,positive_review_ratio,negative_review_ratio,days_on_platform,reviews_per_day,verified_review_ratio,popularity_segment,quality_score
0,b00vrpsgeo,accupressure guide,appstore for android,,Acupressure technique is very ancient and very...,All the pressing point has been explained with...,"{""Release Date"": ""2015"", ""Date first listed on...","{""hi_res"": [null, null, null, null], ""large"": ...","{""title"": [], ""url"": [], ""user_id"": []}",NaN,...,2,1.000000,2,1.000000,0.000000,34,0.058824,1.00,low_coverage,0.342372
1,b076j3sj4g,ac market tips,appstore for android,,Application made by fans for fans!Complete and...,We personally check and use the apps and play ...,"{""Release Date"": ""2017"", ""Date first listed on...","{""hi_res"": [null, null, null, null, null, null...","{""title"": [], ""url"": [], ""user_id"": []}",NaN,...,6,6.000000,1,0.000000,1.000000,1,1.000000,1.00,cold_start,0.000000
2,b01guebbc0,gem shopping network,appstore for android,,Watch Gem Shopping Network Live!,"Live Stream!,Call to shop, ask questions, and ...","{""Release Date"": ""2016"", ""Date first listed on...","{""hi_res"": [null, null, null, null, null, null...","{""title"": [], ""url"": [], ""user_id"": []}",816.0,...,6,0.666667,9,0.666667,0.222222,1048,0.008588,1.00,low_coverage,0.354197
3,b073rdqzfs,rovercraft race your space car,appstore for android,,Play The World Famous Car Crafting Runner with...,14 different planets from the galaxy to race o...,"{""Release Date"": ""2017"", ""Date first listed on...","{""hi_res"": [null, null, null, null, null, null...","{""title"": [], ""url"": [""https://images-na.ssl-i...",154.0,...,0,0.000000,1,1.000000,0.000000,1,1.000000,1.00,cold_start,0.206543
4,b004669psm,corel paintshop pro x4 [old version],software,"all corel,corel,software",Streamlined workspace--easily make powerful ad...,"Photo-editing software with a streamlined, int...","{""Is Discontinued By Manufacturer"": ""No"", ""Lan...","{""hi_res"": [null], ""large"": [""https://m.media-...","{""title"": [], ""url"": [], ""user_id"": []}",139.0,...,6,1.500000,1,1.000000,0.000000,344,0.011628,0.25,low_coverage,0.510100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27792,b003gamzfo,norton 360 version 4.0 1 user / 3 pc [download...,software,"internet security,software,symantec",,"Protects your identity when you buy, bank, and...","{""Language"": ""English"", ""Item model number"": ""...","{""hi_res"": [""https://m.media-amazon.com/images...","{""title"": [], ""url"": [], ""user_id"": []}",136.0,...,0,0.000000,1,1.000000,0.000000,1,1.000000,1.00,cold_start,0.206543
27793,b00894f95k,quickbooks point of sale pro 2013 new user,software,"all intuit,intuit,software",Move beyond the cash register. Intuit QuickBoo...,Buy with confidence from an Intuit Premier Res...,"{""Is Discontinued By Manufacturer"": ""No"", ""Pac...","{""hi_res"": [""https://m.media-amazon.com/images...","{""title"": [], ""url"": [], ""user_id"": []}",9.0,...,3,3.000000,1,0.000000,1.000000,1,1.000000,1.00,cold_start,0.000000
27794,b088jvtv1k,тurbotax 2019 home and business - only for win...,software,"software,tax preparation",TurboTax is tailored to your unique situation—...,TurboTax Home & Business + State is recommende...,"{""Package Dimensions"": ""7.5 x 5.5 x 0.7 inches...","{""hi_res"": [""https://m.media-amazon.com/images...","{""title"": [], ""url"": [], ""user_id"": []}",146.0,...,0,0.000000,0,0.000000,1.000000,1,1.000000,0.00,cold_start,0.000000
27795,b00094ot7c,scansoft pdf converter professional 3.0 [old v...,NaN,"brands,dragon & scansoft by nuance,software","Product Description,ScanSoft PDF Converter Pro...","Powerful document and form creation, conversio...","{""Language"": ""English"", ""Package Dimensions"": ...","{""hi_res"": [null], ""large"": [""https://m.media-...","{""title"": [], ""url"": [], ""user_id"": []}",34.0,...,6,6.000000,0,0.000000,1.000000,1,1.000000,0.00,cold_start,0.000000
27796,b0001h5w9g,hallmark card studio 2005 deluxe,software,"greeting cards,home publishing,lifestyle & hob...",,"Create unique Hallmark cards for any occasion,...",{},"{""hi_res"": [null], ""large"": [""https://m.media-...","{""title"": [], ""url"": [], ""user_id"": []}",44.0,...,0,0.000000,1,1.000000,0.000000,1,1.000000,1.00,cold_start,0.206543

In [4]:
review_df = load_user_item(local_read=True)
review_df

,review_id,asin,parent_asin,user_id,review_date,review_title,review_text,review_images,verified_purchase,helpful_vote,...,review_title_length,review_word_count,is_extreme_rating,is_positive,is_negative,num_review_img,days_since_review,review_year,review_month,recency_weight
0,60496,b017250d16,b017250d16,aexrdwc3ij4ogcfwxumf3kqsndbq,2016-03-14,missing fast forward on cbs all access,cbs all access was east to set up on my amazon...,[],True,28,...,38,106,False,False,False,0,2563,2016,3,8.964110e-04
1,60497,b01msbcrdy,b01msbcrdy,aestczq3vayrtihcyt5arnpop2ya,2020-06-18,needs work,using a roku ultra or a 4k firestick the playb...,[],True,1,...,10,29,False,False,True,0,1006,2020,6,6.365497e-02
2,60498,b06xhzxm27,b06xhzxm27,aestczq3vayrtihcyt5arnpop2ya,2020-01-09,very poor performance on firestick 4k,"substantial pixelation, choppiness loaded with...",[],True,0,...,37,30,True,False,True,0,1167,2020,1,4.096358e-02
3,60499,b01n3uv5uv,b01n3uv5uv,aestczq3vayrtihcyt5arnpop2ya,2019-08-15,good but needs work,the cnbc live app plays perfectly on my roku d...,[],True,4,...,19,69,False,False,False,0,1314,2019,8,2.739113e-02
4,60500,b009p8emck,b009p8emck,afb7qmkbboagqffksudjs4cxgtzq,2018-01-22,"kids shows on demand, freeeee",great way to waste the time and have something...,[],True,6,...,29,35,True,True,False,0,1884,2018,1,5.752557e-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244004,142434,b072c5b374,b072c5b374,ah5umajbbtlqt3rils6lrjefge5q,2020-01-18,no cable provider,cant watch this network unless you give login ...,[],True,0,...,17,21,True,False,True,0,1158,2020,1,4.198549e-02
244005,142435,b006p2y2qk,b006p2y2qk,ahqf4l2z7ebtq6i6winjcvuimhua,2014-03-25,solitaire,fun rainy day game with the grandchildren. bet...,[],True,0,...,9,22,False,True,False,0,3283,2014,3,1.248542e-04
244006,142436,b00p03d4d2,b00p03d4d2,afndg3owkrlv4v2qvzcjk5ecxiaa,2016-05-14,echo dot--great system,echo dot...fabulous! it's everything the websi...,[],True,0,...,22,12,True,True,False,0,2502,2016,5,1.059347e-03
244007,142437,b00wkj07ac,b00wkj07ac,ahwq3lp5tztgmtmmdhjjwqxdgflq,2015-07-19,upgrade worked well,great program updated my fmp12 advanced quite ...,[],True,0,...,19,8,False,False,False,0,2802,2015,7,4.659380e-04
244008,142438,b0000azjvg,b0000azjvg,ah2h5tkjbkp4l6jzpef3ots6ewda,2003-12-13,great research tool,"i've been using onenote since the beta, and ha...",[],False,20,...,19,289,True,True,False,0,7038,2003,12,4.281365e-09